#!/usr/bin/env bash
# Regenerates $STARKIT_HOME/src/registry.gleam from the Scripts in src/scripts/.
#
# Gleam has no runtime reflection, so the list of Scripts has to exist as source. This derives it
# from the directory instead of asking you to maintain a list.
#
# The convention it relies on: every src/scripts/<keyword>.gleam exposes `pub fn script() ->
# starkit.Script`. A file that does not fails the build with a type error naming it, which is the
# intended outcome.
#
# Output is sorted, so running this twice produces a byte-identical file. The Watcher (slice 6) runs
# it on every save, and a file whose mtime moved for no reason would make every Script look Stale.
set -euo pipefail

STARKIT_HOME="${STARKIT_HOME:-$HOME/.starkit}"
SCRIPTS_DIR="$STARKIT_HOME/src/scripts"
REGISTRY="$STARKIT_HOME/src/registry.gleam"

if [ ! -d "$SCRIPTS_DIR" ]; then
	echo "! No $SCRIPTS_DIR — is Starkit installed? Run scripts/install.sh." >&2
	exit 1
fi

# `LC_ALL=C sort` so the order does not depend on the machine's locale.
modules=()
while IFS= read -r path; do
	name="$(basename "$path" .gleam)"
	modules+=("$name")
done < <(find "$SCRIPTS_DIR" -maxdepth 1 -name '*.gleam' -type f | LC_ALL=C sort)

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
	echo "//// Generated by scripts/gen-registry.sh. Do not edit — your changes will be replaced."
	echo "////"
	echo "//// Add a Script by creating src/scripts/<keyword>.gleam; it appears here on the next run."
	echo
	# Import order matches `gleam format`, which sorts alphabetically. Not cosmetic: an unformatted
	# file would be rewritten by `gleam format`, moving its mtime and marking Scripts Stale. Every
	# `scripts/…` sorts before `starkit`, so the Vocabulary import always goes last.
	for name in "${modules[@]}"; do
		echo "import scripts/$name"
	done
	echo "import starkit"
	echo
	echo "/// Every Script the Shelf knows about."
	echo "pub fn all() -> List(starkit.Script) {"
	if [ "${#modules[@]}" -eq 0 ]; then
		# An empty list still has to typecheck, and Gleam cannot infer the element type of [].
		echo "  let scripts: List(starkit.Script) = []"
		echo "  scripts"
	else
		echo "  ["
		for name in "${modules[@]}"; do
			echo "    $name.script(),"
		done
		echo "  ]"
	fi
	echo "}"
} >"$tmp"

if [ -f "$REGISTRY" ] && cmp -s "$tmp" "$REGISTRY"; then
	# Leaving the mtime alone is the point, not an optimisation: see the header.
	echo "= $REGISTRY unchanged (${#modules[@]} Scripts)"
	exit 0
fi

mv "$tmp" "$REGISTRY"
echo "→ $REGISTRY (${#modules[@]} Scripts)"
