import Foundation

/// The one list Gleam cannot derive for itself.
///
/// Gleam has no runtime reflection, so "every **Script** the **Shelf** knows about" has to exist as
/// source. This turns a set of **Keywords** into that source, and it is the whole rule — finding the
/// **Keywords** and writing the file belong to C6, which is where a filesystem is allowed.
///
/// **Byte-identical output for the same input is the point, not tidiness.** `registry.gleam` is one of
/// C5's shared modules, so a file rewritten with the same contents would move its mtime, change
/// nothing, and mark every **Script** **Stale** — see `Staleness` and ADR 0002. That is also why the
/// text below is already `gleam format`-clean: a file Gleam would reformat is a file something else
/// rewrites later.
public enum Registry {
    /// Sorted by UTF-8 bytes rather than by `<`, which is what `LC_ALL=C sort` did when this rule
    /// lived in a shell script — the two agree for every valid Gleam module name and stop agreeing
    /// outside them, and a **Keyword** outside them is a build error naming the file rather than
    /// something to hide here.
    public static func source(for keywords: [String]) -> String {
        let sorted = keywords.sorted { Array($0.utf8).lexicographicallyPrecedes(Array($1.utf8)) }

        var lines = [
            "//// Generated by Starkit. Do not edit — your changes will be replaced.",
            "////",
            "//// Add a Script by creating src/scripts/<keyword>.gleam; it appears here on the next save.",
            "",
        ]
        // Alphabetical, and `starkit` last because every `scripts/…` sorts before it — the order
        // `gleam format` would impose anyway.
        lines += sorted.map { "import scripts/\($0)" }
        lines += ["import starkit", "", "/// Every Script the Shelf knows about.", "pub fn all() -> List(starkit.Script) {"]

        if sorted.isEmpty {
            // `[]` on its own does not typecheck: Gleam cannot infer the element type of an empty
            // list, and the annotation has to go on a binding rather than on the literal.
            lines += ["  let scripts: List(starkit.Script) = []", "  scripts"]
        } else {
            lines += ["  ["] + sorted.map { "    \($0).script()," } + ["  ]"]
        }

        lines += ["}", ""]
        return lines.joined(separator: "\n")
    }
}
