import Foundation
import Testing

@testable import StarkitCore

/// The generated module, pinned as text: `gleam build` fails loudly on it, but C5's staleness check
/// fails *silently* — a byte that moves for no reason marks every **Script** **Stale**.
struct RegistryTests {
    @Test("the whole module, for the five Scripts the seed ships")
    func fiveScripts() {
        let source = Registry.source(for: ["clean", "link", "personal", "work", "youtube"])
        #expect(
            source == """
                //// Generated by Starkit. Do not edit — your changes will be replaced.
                ////
                //// Add a Script by creating src/scripts/<keyword>.gleam; it appears here on the next save.

                import scripts/clean
                import scripts/link
                import scripts/personal
                import scripts/work
                import scripts/youtube
                import starkit

                /// Every Script the Shelf knows about.
                pub fn all() -> List(starkit.Script) {
                  [
                    clean.script(),
                    link.script(),
                    personal.script(),
                    work.script(),
                    youtube.script(),
                  ]
                }

                """
        )
    }

    @Test("no Scripts still produces a module that compiles")
    func noScripts() {
        let source = Registry.source(for: [])
        #expect(
            source == """
                //// Generated by Starkit. Do not edit — your changes will be replaced.
                ////
                //// Add a Script by creating src/scripts/<keyword>.gleam; it appears here on the next save.

                import starkit

                /// Every Script the Shelf knows about.
                pub fn all() -> List(starkit.Script) {
                  let scripts: List(starkit.Script) = []
                  scripts
                }

                """
        )
    }

    @Test("the order is the input's, sorted, so the same Scripts always produce the same bytes")
    func orderDoesNotDependOnTheCaller() {
        let one = Registry.source(for: ["youtube", "clean", "work"])
        let another = Registry.source(for: ["work", "youtube", "clean"])
        #expect(one == another)
        #expect(one.contains("import scripts/clean\nimport scripts/work\nimport scripts/youtube\n"))
    }

    // `_` is 0x5F and every letter is above it, so `link_check` sorts before `linkedin` — the answer
    // `LC_ALL=C sort` gave when this rule was a shell script.
    @Test("an underscore sorts before a letter, as it did under LC_ALL=C")
    func underscoreSortsByByte() {
        let source = Registry.source(for: ["linkedin", "link_check"])
        #expect(source.contains("import scripts/link_check\nimport scripts/linkedin\n"))
    }

    // The trailing newline is load-bearing for the same reason everything else here is: a file
    // ending without one is a file `gleam format` rewrites.
    @Test("the module ends with exactly one newline")
    func trailingNewline() {
        let source = Registry.source(for: ["work"])
        #expect(source.hasSuffix("}\n"))
        #expect(!source.hasSuffix("}\n\n"))
    }
}
