import Foundation
import Testing

@testable import StarkitCore

/// The generated module, pinned as text.
///
/// Worth pinning at all because two things read this file and neither of them is a person: `gleam
/// build`, which fails loudly, and C5's staleness check, which fails *silently* — a byte that moves
/// for no reason marks every **Script** **Stale**, and nothing says so except **Scripts** refusing
/// one at a time.
struct RegistryTests {
    @Test("the whole module, for the five Scripts the seed ships")
    func fiveScripts() {
        let source = Registry.source(for: ["clean", "link", "personal", "work", "youtube"])
        #expect(
            source == """
                //// Generated by Starkit. Do not edit — your changes will be replaced.
                ////
                //// Add a Script by creating src/scripts/<keyword>.gleam; it appears here on the next save.

                import scripts/clean
                import scripts/link
                import scripts/personal
                import scripts/work
                import scripts/youtube
                import starkit

                /// Every Script the Shelf knows about.
                pub fn all() -> List(starkit.Script) {
                  [
                    clean.script(),
                    link.script(),
                    personal.script(),
                    work.script(),
                    youtube.script(),
                  ]
                }

                """
        )
    }

    // An empty list cannot be written `[]`: Gleam has no element type to infer, and the annotation
    // only goes on a binding. Deleting every Script has to leave a file that still compiles, or the
    // menu bar goes red for a home that is merely empty.
    @Test("no Scripts still produces a module that compiles")
    func noScripts() {
        let source = Registry.source(for: [])
        #expect(
            source == """
                //// Generated by Starkit. Do not edit — your changes will be replaced.
                ////
                //// Add a Script by creating src/scripts/<keyword>.gleam; it appears here on the next save.

                import starkit

                /// Every Script the Shelf knows about.
                pub fn all() -> List(starkit.Script) {
                  let scripts: List(starkit.Script) = []
                  scripts
                }

                """
        )
    }

    @Test("the order is the input's, sorted, so the same Scripts always produce the same bytes")
    func orderDoesNotDependOnTheCaller() {
        let one = Registry.source(for: ["youtube", "clean", "work"])
        let another = Registry.source(for: ["work", "youtube", "clean"])
        #expect(one == another)
        #expect(one.contains("import scripts/clean\nimport scripts/work\nimport scripts/youtube\n"))
    }

    // `_` is 0x5F and every letter is above it, so `link_check` sorts before `linkedin` — the answer
    // `LC_ALL=C sort` gave when this rule was a shell script, and the same answer the machine's own
    // locale gives for the lowercase-ASCII-and-underscore names Gleam allows. The two only part
    // company outside them, which is why the rule compares bytes and does not have to care.
    @Test("an underscore sorts before a letter, as it did under LC_ALL=C")
    func underscoreSortsByByte() {
        let source = Registry.source(for: ["linkedin", "link_check"])
        #expect(source.contains("import scripts/link_check\nimport scripts/linkedin\n"))
    }

    // The trailing newline is load-bearing for the same reason everything else here is: a file
    // ending without one is a file `gleam format` rewrites.
    @Test("the module ends with exactly one newline")
    func trailingNewline() {
        let source = Registry.source(for: ["work"])
        #expect(source.hasSuffix("}\n"))
        #expect(!source.hasSuffix("}\n\n"))
    }
}
